/-
Copyright (c) 2026 LeanLevy Contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: LeanLevy Contributors
-/
import Mathlib.MeasureTheory.PiSystem
import LeanLevy.Probability.IndependenceGrouping
import LeanLevy.RandomMeasure.PoissonRandomMeasure

/-!
# Evaluation sigma-algebras of a Poisson random measure

Given the `poissonRandomMeasure K X` of a Poisson point family, a natural family of sub-sigma-algebras
on the sample space `Ω` records only the information carried by the counts inside a region `R ⊆ E`.
For a measurable subset `B ⊆ R` of finite intensity mass, the evaluation `ω ↦ poissonRandomMeasure K X ω B`
is a random variable, and the **evaluation sigma-algebra** `prmEvalSigma K X m R` is the least
sigma-algebra making all such evaluations measurable. This file defines that sigma-algebra, records its
basic order properties, and exhibits the generating π-system of finite intersections of evaluation
preimages.

## Main definitions

* `ProbabilityTheory.prmEvalIndex` — the index of admissible evaluation sets inside a region: measurable
  subsets of finite intensity mass.
* `ProbabilityTheory.prmEvalSigma` — the sigma-algebra generated by the finite-mass evaluations of the
  random measure inside a region `R`.
* `ProbabilityTheory.prmEvalPiSystem` — the generating π-system of finite intersections of evaluation
  preimages inside `R`.

## Main results

* `ProbabilityTheory.prmEvalSigma_mono` — the evaluation sigma-algebras grow with the region.
* `ProbabilityTheory.prmEvalSigma_le` — each evaluation sigma-algebra is a sub-sigma-algebra of the
  ambient one, given measurability of the counts and points.
* `ProbabilityTheory.measurable_prmEvalSigma_apply` — every finite-mass evaluation inside `R` is
  measurable with respect to `prmEvalSigma K X m R`.
* `ProbabilityTheory.measurable_lintegral_poissonRandomMeasure_prmEvalSigma` — the Lebesgue integral
  of a region-supported function against the random measure is measurable with respect to the
  evaluation sigma-algebra of the region.
* `ProbabilityTheory.isPiSystem_prmEvalPiSystem` — the generating family is a π-system.
* `ProbabilityTheory.prmEvalSigma_eq_generateFrom` — the evaluation sigma-algebra is generated by that
  π-system.
* `ProbabilityTheory.indepFun_poissonRandomMeasure_families` — two finite families of finite-mass
  evaluation sets, mutually disjoint across the families, give independent evaluation processes.
* `ProbabilityTheory.indep_prmEvalSigma` — **the Poisson random measure is independently scattered at
  the sigma-algebra level:** the evaluation sigma-algebras of two disjoint regions are independent.
* `ProbabilityTheory.iIndepFun_poissonRandomMeasure_families` — finitely many finite families of
  finite-mass evaluation sets, mutually disjoint across the families, give mutually independent
  evaluation processes.
* `ProbabilityTheory.iIndep_prmEvalSigma` — **the Poisson random measure is mutually independently
  scattered:** the evaluation sigma-algebras of finitely many pairwise-disjoint regions are mutually
  independent.
-/

open MeasureTheory

open scoped ENNReal

namespace ProbabilityTheory

variable {Ω E : Type} [MeasurableSpace Ω] [MeasurableSpace E] {K : ℕ → Ω → ℕ} {X : ℕ → ℕ → Ω → E}
  {m : Measure E}

/-- The index of admissible evaluation sets inside a region: measurable, contained, finite mass. -/
def prmEvalIndex (m : Measure E) (R : Set E) : Type :=
  {B : Set E // MeasurableSet B ∧ B ⊆ R ∧ m B < ⊤}

/-- The σ-algebra generated by the finite-mass evaluations of the random measure inside `R`. -/
@[reducible] noncomputable def prmEvalSigma (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E)
    (R : Set E) : MeasurableSpace Ω :=
  ⨆ B : prmEvalIndex m R,
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebras grow with the region: a larger region admits more evaluation sets. -/
theorem prmEvalSigma_mono {R S : Set E} (hRS : R ⊆ S) :
    prmEvalSigma K X m R ≤ prmEvalSigma K X m S :=
  iSup_le fun B => le_iSup_of_le ⟨B.1, B.2.1, B.2.2.1.trans hRS, B.2.2.2⟩ le_rfl

/-- Each evaluation σ-algebra is a sub-σ-algebra of the ambient one, provided the counts and points
of the underlying family are measurable. -/
theorem prmEvalSigma_le (hK : ∀ k, Measurable (K k)) (hX : ∀ k n, Measurable (X k n)) (R : Set E) :
    prmEvalSigma K X m R ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun B => (measurable_poissonRandomMeasure_apply hK hX B.2.1).comap_le

omit [MeasurableSpace Ω] in
/-- Every finite-mass evaluation inside `R` is measurable with respect to `prmEvalSigma K X m R`. -/
theorem measurable_prmEvalSigma_apply {B R : Set E} (hB : MeasurableSet B) (hBR : B ⊆ R)
    (hfin : m B < ⊤) :
    Measurable[prmEvalSigma K X m R] fun ω => poissonRandomMeasure K X ω B :=
  Measurable.of_comap_le <| le_iSup (fun B' : prmEvalIndex m R =>
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B'.1) inferInstance)
    ⟨B, hB, hBR, hfin⟩

omit [MeasurableSpace Ω] in
/-- The Lebesgue integral of a region-supported function against the random measure is measurable
with respect to the evaluation σ-algebra of the region. Every nonzero-value fiber of a monotone
simple-function approximant of `g` lies inside `R`, so the approximant's integral is a finite sum of
finite-mass evaluations inside `R`; the integral is their countable supremum. -/
theorem measurable_lintegral_poissonRandomMeasure_prmEvalSigma {R : Set E}
    (_hR : MeasurableSet R) (hRfin : m R < ⊤) {g : E → ℝ≥0∞} (hg : Measurable g)
    (hgR : ∀ x, x ∉ R → g x = 0) :
    Measurable[prmEvalSigma K X m R]
      fun ω => ∫⁻ x, g x ∂(poissonRandomMeasure K X ω) := by
  -- every nonzero-value fiber of an approximant sits inside `R`
  have hfiber : ∀ (n : ℕ) {y : ℝ≥0∞}, y ≠ 0 → SimpleFunc.eapprox g n ⁻¹' {y} ⊆ R := by
    intro n y hy x hx
    rw [Set.mem_preimage, Set.mem_singleton_iff] at hx
    by_contra hxR
    have hle : SimpleFunc.eapprox g n x ≤ g x := by
      have h := le_iSup (fun k => SimpleFunc.eapprox g k x) n
      rwa [SimpleFunc.iSup_eapprox_apply hg x] at h
    rw [hx, hgR x hxR, le_zero_iff] at hle
    exact hy hle
  -- each approximant's simple-function integral is measurable in `prmEvalSigma R`
  have hsimple : ∀ n : ℕ, Measurable[prmEvalSigma K X m R]
      fun ω => (SimpleFunc.eapprox g n).lintegral (poissonRandomMeasure K X ω) := by
    intro n
    simp only [SimpleFunc.lintegral]
    refine Finset.measurable_sum _ fun y _ => ?_
    by_cases hy : y = 0
    · simp only [hy, zero_mul]; exact measurable_const
    · exact (measurable_prmEvalSigma_apply ((SimpleFunc.eapprox g n).measurableSet_fiber y)
        (hfiber n hy) (lt_of_le_of_lt (measure_mono (hfiber n hy)) hRfin)).const_mul y
  -- the integral is the countable supremum of the approximants' integrals
  have hcongr : (fun ω => ∫⁻ x, g x ∂(poissonRandomMeasure K X ω))
      = fun ω => ⨆ n : ℕ, (SimpleFunc.eapprox g n).lintegral (poissonRandomMeasure K X ω) :=
    funext fun ω => lintegral_eq_iSup_eapprox_lintegral hg
  rw [hcongr]
  exact Measurable.iSup hsimple

/-- The generating π-system: finite intersections of evaluation preimages inside `R`. -/
def prmEvalPiSystem (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E) (R : Set E) :
    Set (Set Ω) :=
  piiUnionInter (fun B : prmEvalIndex m R =>
    {A | MeasurableSet[MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1)
      inferInstance] A}) Set.univ

omit [MeasurableSpace Ω] in
/-- The generating family of evaluation preimages is a π-system. -/
theorem isPiSystem_prmEvalPiSystem {R : Set E} : IsPiSystem (prmEvalPiSystem K X m R) :=
  isPiSystem_piiUnionInter _ (fun B : prmEvalIndex m R => @MeasurableSpace.isPiSystem_measurableSet Ω
    (MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)) Set.univ

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebra is generated by its π-system of finite intersections of evaluation
preimages. -/
theorem prmEvalSigma_eq_generateFrom (R : Set E) :
    prmEvalSigma K X m R = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R) := by
  show (⨆ B : prmEvalIndex m R,
      MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)
    = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R)
  rw [prmEvalPiSystem,
    generateFrom_piiUnionInter_measurableSet
      (fun B : prmEvalIndex m R =>
        MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance) Set.univ,
    iSup_univ]

/-! ### Atomization of a finite family of evaluation sets

To reduce cross-family independence to the mutual independence of counts over a pairwise disjoint
family, we refine a finite family `B : ι → Set E` into its atoms. For a finset `J ⊆ ι`, the atom
`evalAtom B J` collects the points lying in `B i` for every `i ∈ J` and outside `B i` for every
`i ∉ J`. Distinct atoms are disjoint, each atom sits inside every `B i` with `i ∈ J`, and `B i` is
the disjoint union of the atoms whose index set contains `i`. The empty index set is sent to `∅` so
that every atom has finite intensity mass. -/

section Atomization

variable {ι : Type} {B : ι → Set E}

/-- The atom of a finite family `B : ι → Set E` at a finset `J`: the points lying in `B i` for every
`i ∈ J` and outside `B i` for every `i ∉ J`; the empty index set is sent to `∅`. -/
private def evalAtom (B : ι → Set E) (J : Finset ι) : Set E :=
  if J.Nonempty then (⋂ i ∈ J, B i) ∩ ⋂ i ∉ J, (B i)ᶜ else ∅

omit [MeasurableSpace E] in
private lemma evalAtom_of_nonempty {J : Finset ι} (hJ : J.Nonempty) :
    evalAtom B J = (⋂ i ∈ J, B i) ∩ ⋂ i ∉ J, (B i)ᶜ :=
  if_pos hJ

omit [MeasurableSpace E] in
private lemma evalAtom_empty : evalAtom B ∅ = ∅ :=
  if_neg (by simp)

omit [MeasurableSpace E] in
private lemma evalAtom_subset {J : Finset ι} {i : ι} (hiJ : i ∈ J) :
    evalAtom B J ⊆ B i := by
  rw [evalAtom_of_nonempty ⟨i, hiJ⟩]
  exact Set.inter_subset_left.trans (Set.iInter₂_subset i hiJ)

omit [MeasurableSpace E] in
private lemma evalAtom_subset_compl {J : Finset ι} {i : ι} (hJ : J.Nonempty)
    (hiJ : i ∉ J) : evalAtom B J ⊆ (B i)ᶜ := by
  rw [evalAtom_of_nonempty hJ]
  exact Set.inter_subset_right.trans (Set.iInter₂_subset i hiJ)

omit [MeasurableSpace E] in
private lemma evalAtom_subset_iUnion {J : Finset ι} :
    evalAtom B J ⊆ ⋃ i, B i := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty]; exact Set.empty_subset _
  · obtain ⟨i, hi⟩ := hJ
    exact (evalAtom_subset hi).trans (Set.subset_iUnion _ i)

private lemma measurableSet_evalAtom [Fintype ι] (hBm : ∀ i, MeasurableSet (B i))
    (J : Finset ι) : MeasurableSet (evalAtom B J) := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty]; exact MeasurableSet.empty
  · rw [evalAtom_of_nonempty hJ]
    exact (Finset.measurableSet_biInter J fun i _ => hBm i).inter
      (MeasurableSet.iInter fun i => MeasurableSet.iInter fun _ => (hBm i).compl)

private lemma measure_evalAtom_lt_top (hBfin : ∀ i, m (B i) < ⊤) (J : Finset ι) :
    m (evalAtom B J) < ⊤ := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty, measure_empty]; exact ENNReal.zero_lt_top
  · obtain ⟨i, hi⟩ := hJ
    exact lt_of_le_of_lt (measure_mono (evalAtom_subset hi)) (hBfin i)

omit [MeasurableSpace E] in
private lemma disjoint_evalAtom_of_mem_notMem {J J' : Finset ι} {i : ι}
    (hiJ : i ∈ J) (hiJ' : i ∉ J') : Disjoint (evalAtom B J) (evalAtom B J') := by
  rcases J'.eq_empty_or_nonempty with rfl | hJ'
  · rw [evalAtom_empty]; exact disjoint_bot_right
  · exact Disjoint.mono (evalAtom_subset hiJ) (evalAtom_subset_compl hJ' hiJ') disjoint_compl_right

omit [MeasurableSpace E] in
private lemma pairwise_disjoint_evalAtom :
    Pairwise (Function.onFun Disjoint (evalAtom B)) := by
  intro J J' hJJ'
  show Disjoint (evalAtom B J) (evalAtom B J')
  have hne : ¬ ∀ i, i ∈ J ↔ i ∈ J' := fun h => hJJ' (Finset.ext h)
  push Not at hne
  obtain ⟨i, hi⟩ := hne
  rcases hi with ⟨hiJ, hiJ'⟩ | ⟨hiJ, hiJ'⟩
  · exact disjoint_evalAtom_of_mem_notMem hiJ hiJ'
  · exact (disjoint_evalAtom_of_mem_notMem hiJ' hiJ).symm

omit [MeasurableSpace E] in
private lemma biUnion_evalAtom [Fintype ι] [DecidableEq ι] (i : ι) :
    B i = ⋃ J ∈ Finset.univ.filter (fun J => i ∈ J), evalAtom B J := by
  classical
  ext x
  simp only [Set.mem_iUnion, Finset.mem_filter, Finset.mem_univ, true_and, exists_prop]
  constructor
  · intro hx
    refine ⟨Finset.univ.filter (fun j => x ∈ B j), Finset.mem_filter.mpr ⟨Finset.mem_univ i, hx⟩, ?_⟩
    have hne : (Finset.univ.filter (fun j => x ∈ B j)).Nonempty :=
      ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hx⟩⟩
    rw [evalAtom_of_nonempty hne]
    refine ⟨Set.mem_iInter₂.mpr fun j hj => (Finset.mem_filter.mp hj).2, ?_⟩
    exact Set.mem_iInter₂.mpr fun j hj hxBj =>
      hj (Finset.mem_filter.mpr ⟨Finset.mem_univ j, hxBj⟩)
  · rintro ⟨J, hiJ, hxJ⟩
    exact evalAtom_subset hiJ hxJ

omit [MeasurableSpace Ω] in
private lemma poissonRandomMeasure_apply_biUnion_evalAtom [Fintype ι] [DecidableEq ι]
    (hBm : ∀ i, MeasurableSet (B i)) (ω : Ω) (i : ι) :
    poissonRandomMeasure K X ω (B i)
      = ∑ J ∈ Finset.univ.filter (fun J => i ∈ J),
          poissonRandomMeasure K X ω (evalAtom B J) := by
  conv_lhs => rw [biUnion_evalAtom (B := B) i]
  rw [measure_biUnion_finset (pairwise_disjoint_evalAtom.set_pairwise _)
    (fun J _ => measurableSet_evalAtom hBm J)]

end Atomization

/-! ### Independence across disjoint families

The Poisson random measure is independently scattered: evaluations over regions that are set-wise
disjoint carry no information about one another. We first prove the process-level statement for two
finite families and then promote it to independence of the full evaluation sigma-algebras. -/

section Independence

variable {μ : Measure Ω} [SigmaFinite m] [Nonempty E]

/-- Mutual cross-family independence: finitely many finite families of finite-mass evaluation
sets, with every set of family `i` disjoint from every set of family `j` for `i ≠ j` (no
disjointness required within a family), give mutually independent evaluation processes. -/
theorem iIndepFun_poissonRandomMeasure_families [IsProbabilityMeasure μ]
    (hd : IsPoissonPointFamily K X m μ) {ι : Type} [Fintype ι] {ιB : ι → Type}
    [∀ i, Fintype (ιB i)] {B : ∀ i, ιB i → Set E}
    (hBm : ∀ i b, MeasurableSet (B i b)) (hBfin : ∀ i b, m (B i b) < ⊤)
    (hBdisj : ∀ i j, i ≠ j → ∀ b b', Disjoint (B i b) (B j b')) :
    iIndepFun (fun i ω (b : ιB i) => poissonRandomMeasure K X ω (B i b)) μ := by
  classical
  -- Refine every family simultaneously into the atoms indexed by `Σ i, Finset (ιB i)`.
  set A : (Σ i, Finset (ιB i)) → Set E := fun σ => evalAtom (B σ.1) σ.2 with hA
  have hAm : ∀ σ, MeasurableSet (A σ) := fun σ => measurableSet_evalAtom (hBm σ.1) σ.2
  have hAfin : ∀ σ, m (A σ) < ⊤ := fun σ => measure_evalAtom_lt_top (hBfin σ.1) σ.2
  -- Atoms of the same family are disjoint by index set; atoms of different families are disjoint
  -- because the families are set-wise disjoint.
  have hAdisj : Pairwise (Function.onFun Disjoint A) := by
    rintro ⟨i, J⟩ ⟨i', J'⟩ hne
    show Disjoint (evalAtom (B i) J) (evalAtom (B i') J')
    by_cases hii : i = i'
    · subst hii
      exact pairwise_disjoint_evalAtom (fun hJ => hne (by rw [hJ]))
    · have hU : Disjoint (⋃ b, B i b) (⋃ b', B i' b') :=
        Set.disjoint_iUnion_left.mpr fun b =>
          Set.disjoint_iUnion_right.mpr fun b' => hBdisj i i' hii b b'
      exact hU.mono evalAtom_subset_iUnion evalAtom_subset_iUnion
  have hiIndep := iIndepFun_poissonRandomMeasure_apply hd hAm hAfin hAdisj
  have hmeas : ∀ σ, Measurable (fun ω => poissonRandomMeasure K X ω (A σ)) :=
    fun σ => measurable_poissonRandomMeasure_apply hd.measurable_count hd.measurable_point (hAm σ)
  -- The fibers `{σ | σ.1 = i}` are pairwise disjoint, so grouping the counts along them preserves
  -- mutual independence.
  have hSdisj : Pairwise (Function.onFun Disjoint
      (fun i => {σ : Σ i, Finset (ιB i) | σ.1 = i})) := by
    intro i i' hii
    show Disjoint {σ : Σ i, Finset (ιB i) | σ.1 = i} {σ | σ.1 = i'}
    rw [Set.disjoint_left]
    rintro σ hσ hσ'
    simp only [Set.mem_setOf_eq] at hσ hσ'
    exact hii (hσ.symm.trans hσ')
  have hblocks := hiIndep.setRestrict_of_pairwiseDisjoint hmeas hSdisj
  -- Reassemble each family from its atoms: `N ω (B i b) = ∑_{J ∋ b} N ω (evalAtom (B i) J)`.
  set G : ∀ i, (↥{σ : Σ i, Finset (ιB i) | σ.1 = i} → ℝ≥0∞) → (ιB i → ℝ≥0∞) :=
    fun i g b => ∑ J ∈ Finset.univ.filter (fun J => b ∈ J), g ⟨⟨i, J⟩, rfl⟩ with hG
  have hGmeas : ∀ i, Measurable (G i) := fun i => by
    rw [hG]
    exact measurable_pi_lambda _ fun b =>
      Finset.measurable_sum _ fun J _ => measurable_pi_apply _
  have hcomp := hblocks.comp G hGmeas
  have heq : (fun i ω (b : ιB i) => poissonRandomMeasure K X ω (B i b))
      = fun i => G i ∘ (fun ω => ({σ : Σ i, Finset (ιB i) | σ.1 = i}).restrict
          fun σ => poissonRandomMeasure K X ω (A σ)) := by
    funext i ω b
    rw [poissonRandomMeasure_apply_biUnion_evalAtom (hBm i) ω b]
    simp only [Function.comp_apply, hG, Set.restrict_apply, hA]
  rw [heq]
  exact hcomp

/-- **The Poisson random measure is mutually independently scattered:** the evaluation
σ-algebras of finitely many pairwise-disjoint regions are mutually independent. -/
theorem iIndep_prmEvalSigma [IsProbabilityMeasure μ] (hd : IsPoissonPointFamily K X m μ)
    {ι : Type} [Fintype ι] {R : ι → Set E} (hR : Pairwise (Function.onFun Disjoint R)) :
    iIndep (fun i => prmEvalSigma K X m (R i)) μ := by
  classical
  refine iIndepSets.iIndep
    (fun i => prmEvalSigma_le hd.measurable_count hd.measurable_point (R i))
    (fun i => prmEvalPiSystem K X m (R i))
    (fun _ => isPiSystem_prmEvalPiSystem)
    (fun i => prmEvalSigma_eq_generateFrom (R i)) ?_
  rw [iIndepSets_iff]
  intro u f hf
  -- Unpack each π-system element `f i` as a finite intersection of evaluation preimages inside `R i`.
  have hmem : ∀ i : ↥u, f i.1 ∈ prmEvalPiSystem K X m (R i.1) := fun i => hf i.1 i.2
  choose t _hts g hg hfeq using hmem
  -- Each intersected preimage is the preimage of a measurable set under a count evaluation.
  have hUspec : ∀ (i : ↥u) (C : ↥(t i)), ∃ U, MeasurableSet U ∧
      (fun ω => poissonRandomMeasure K X ω (C.1.1 : Set E)) ⁻¹' U = g i C.1 :=
    fun i C => MeasurableSpace.measurableSet_comap.mp (hg i C.1 C.2)
  choose U hUm hUeq using hUspec
  -- The families `C ↦ C.1.1` over `i : ↥u` are cross-disjoint since the regions `R` are.
  have hfam := iIndepFun_poissonRandomMeasure_families hd
    (ιB := fun i : ↥u => ↥(t i)) (B := fun (i : ↥u) (C : ↥(t i)) => (C.1.1 : Set E))
    (fun i C => C.1.2.1) (fun i C => C.1.2.2.2)
    (fun i j hij C C' => (hR (Subtype.coe_ne_coe.mpr hij)).mono C.1.2.2.1 C'.1.2.2.1)
  -- Each `f i` is the joint preimage of the product boxes `Set.univ.pi (U i)`.
  have hpre : ∀ i : ↥u, (fun ω (C : ↥(t i)) => poissonRandomMeasure K X ω C.1.1) ⁻¹'
      (Set.univ.pi (U i)) = f i.1 := by
    intro i
    rw [hfeq i]
    ext ω
    simp only [Set.mem_preimage, Set.mem_pi, Set.mem_univ, true_implies, Set.mem_iInter]
    constructor
    · intro h B hB
      have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω (⟨B, hB⟩ : ↥(t i)).1.1) ⁻¹'
          (U i ⟨B, hB⟩) := h ⟨B, hB⟩
      rw [hUeq i ⟨B, hB⟩] at hmem
      exact hmem
    · intro h C
      have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω C.1.1) ⁻¹' (U i C) := by
        rw [hUeq i C]; exact h C.1 C.2
      exact hmem
  -- The mutual product identity over `↥u`, reindexed back to `u`.
  have hkey := hfam.measure_inter_preimage_eq_mul (Finset.univ : Finset ↥u)
    (sets := fun i => Set.univ.pi (U i)) (fun i _ => MeasurableSet.univ_pi (hUm i))
  simp only [hpre] at hkey
  have hI : (⋂ i ∈ (Finset.univ : Finset ↥u), f i.1) = ⋂ i ∈ u, f i := by
    rw [← Finset.set_biInter_coe, Finset.coe_univ, Set.biInter_univ]
    exact Set.iInter_subtype (· ∈ u) fun i => f i.1
  rw [Finset.prod_coe_sort u fun j => μ (f j), hI] at hkey
  exact hkey

/-- Cross-family independence: two finite families of finite-mass evaluation sets, with every set of
the first family disjoint from every set of the second (no disjointness required within a family),
give independent evaluation processes. -/
theorem indepFun_poissonRandomMeasure_families [IsProbabilityMeasure μ]
    (hd : IsPoissonPointFamily K X m μ) {ιB ιC : Type} [Fintype ιB] [Fintype ιC]
    {B : ιB → Set E} {C : ιC → Set E}
    (hBm : ∀ i, MeasurableSet (B i)) (hCm : ∀ j, MeasurableSet (C j))
    (hBfin : ∀ i, m (B i) < ⊤) (hCfin : ∀ j, m (C j) < ⊤)
    (hBC : ∀ i j, Disjoint (B i) (C j)) :
    IndepFun (fun ω (i : ιB) => poissonRandomMeasure K X ω (B i))
      (fun ω (j : ιC) => poissonRandomMeasure K X ω (C j)) μ := by
  classical
  -- Package the two families as a `Bool`-indexed family and read off the two-index independence.
  haveI : ∀ b : Bool, Fintype (bif b then ιB else ιC) := by
    rintro (_ | _)
    · exact (inferInstance : Fintype ιC)
    · exact (inferInstance : Fintype ιB)
  have key := iIndepFun_poissonRandomMeasure_families hd
    (ιB := fun b : Bool => bif b then ιB else ιC) (B := Bool.rec C B)
    (fun i => by cases i <;> assumption) (fun i => by cases i <;> assumption)
    (by
      rintro (_ | _) (_ | _) hij b b'
      · exact absurd rfl hij
      · exact (hBC b' b).symm
      · exact hBC b b'
      · exact absurd rfl hij)
  exact key.indepFun (i := true) (j := false) (by decide)

/-- **The Poisson random measure is independently scattered at the sigma-algebra level:** the
evaluation sigma-algebras of two disjoint regions are independent. -/
theorem indep_prmEvalSigma [IsProbabilityMeasure μ] (hd : IsPoissonPointFamily K X m μ)
    {R S : Set E} (hRS : Disjoint R S) :
    Indep (prmEvalSigma K X m R) (prmEvalSigma K X m S) μ := by
  classical
  -- The `Bool`-indexed pair `{R, S}` is pairwise disjoint, so the mutual scattering specializes.
  have hpair : Pairwise (Function.onFun Disjoint (fun b : Bool => bif b then R else S)) := by
    rintro (_ | _) (_ | _) hij
    · exact absurd rfl hij
    · exact hRS.symm
    · exact hRS
    · exact absurd rfl hij
  exact (iIndep_prmEvalSigma hd hpair).indep (i := true) (j := false) (by decide)

end Independence

end ProbabilityTheory
