/-
Copyright (c) 2026 LeanLevy Contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: LeanLevy Contributors
-/
import Mathlib.MeasureTheory.PiSystem
import LeanLevy.RandomMeasure.PoissonRandomMeasure

/-!
# Evaluation sigma-algebras of a Poisson random measure

Given the `poissonRandomMeasure K X` of a Poisson point family, a natural family of sub-sigma-algebras
on the sample space `Ω` records only the information carried by the counts inside a region `R ⊆ E`.
For a measurable subset `B ⊆ R` of finite intensity mass, the evaluation `ω ↦ poissonRandomMeasure K X ω B`
is a random variable, and the **evaluation sigma-algebra** `prmEvalSigma K X m R` is the least
sigma-algebra making all such evaluations measurable. This file defines that sigma-algebra, records its
basic order properties, and exhibits the generating π-system of finite intersections of evaluation
preimages.

## Main definitions

* `ProbabilityTheory.prmEvalIndex` — the index of admissible evaluation sets inside a region: measurable
  subsets of finite intensity mass.
* `ProbabilityTheory.prmEvalSigma` — the sigma-algebra generated by the finite-mass evaluations of the
  random measure inside a region `R`.
* `ProbabilityTheory.prmEvalPiSystem` — the generating π-system of finite intersections of evaluation
  preimages inside `R`.

## Main results

* `ProbabilityTheory.prmEvalSigma_mono` — the evaluation sigma-algebras grow with the region.
* `ProbabilityTheory.prmEvalSigma_le` — each evaluation sigma-algebra is a sub-sigma-algebra of the
  ambient one, given measurability of the counts and points.
* `ProbabilityTheory.measurable_prmEvalSigma_apply` — every finite-mass evaluation inside `R` is
  measurable with respect to `prmEvalSigma K X m R`.
* `ProbabilityTheory.isPiSystem_prmEvalPiSystem` — the generating family is a π-system.
* `ProbabilityTheory.prmEvalSigma_eq_generateFrom` — the evaluation sigma-algebra is generated by that
  π-system.
-/

open MeasureTheory

namespace ProbabilityTheory

variable {Ω E : Type} [MeasurableSpace Ω] [MeasurableSpace E] {K : ℕ → Ω → ℕ} {X : ℕ → ℕ → Ω → E}
  {m : Measure E}

/-- The index of admissible evaluation sets inside a region: measurable, contained, finite mass. -/
def prmEvalIndex (m : Measure E) (R : Set E) : Type :=
  {B : Set E // MeasurableSet B ∧ B ⊆ R ∧ m B < ⊤}

/-- The σ-algebra generated by the finite-mass evaluations of the random measure inside `R`. -/
noncomputable def prmEvalSigma (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E)
    (R : Set E) : MeasurableSpace Ω :=
  ⨆ B : prmEvalIndex m R,
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebras grow with the region: a larger region admits more evaluation sets. -/
theorem prmEvalSigma_mono {R S : Set E} (hRS : R ⊆ S) :
    prmEvalSigma K X m R ≤ prmEvalSigma K X m S :=
  iSup_le fun B => le_iSup_of_le ⟨B.1, B.2.1, B.2.2.1.trans hRS, B.2.2.2⟩ le_rfl

/-- Each evaluation σ-algebra is a sub-σ-algebra of the ambient one, provided the counts and points
of the underlying family are measurable. -/
theorem prmEvalSigma_le (hK : ∀ k, Measurable (K k)) (hX : ∀ k n, Measurable (X k n)) (R : Set E) :
    prmEvalSigma K X m R ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun B => (measurable_poissonRandomMeasure_apply hK hX B.2.1).comap_le

omit [MeasurableSpace Ω] in
/-- Every finite-mass evaluation inside `R` is measurable with respect to `prmEvalSigma K X m R`. -/
theorem measurable_prmEvalSigma_apply {B R : Set E} (hB : MeasurableSet B) (hBR : B ⊆ R)
    (hfin : m B < ⊤) :
    Measurable[prmEvalSigma K X m R] fun ω => poissonRandomMeasure K X ω B :=
  Measurable.of_comap_le <| le_iSup (fun B' : prmEvalIndex m R =>
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B'.1) inferInstance)
    ⟨B, hB, hBR, hfin⟩

/-- The generating π-system: finite intersections of evaluation preimages inside `R`. -/
def prmEvalPiSystem (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E) (R : Set E) :
    Set (Set Ω) :=
  piiUnionInter (fun B : prmEvalIndex m R =>
    {A | MeasurableSet[MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1)
      inferInstance] A}) Set.univ

omit [MeasurableSpace Ω] in
/-- The generating family of evaluation preimages is a π-system. -/
theorem isPiSystem_prmEvalPiSystem {R : Set E} : IsPiSystem (prmEvalPiSystem K X m R) :=
  isPiSystem_piiUnionInter _ (fun B : prmEvalIndex m R => @MeasurableSpace.isPiSystem_measurableSet Ω
    (MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)) Set.univ

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebra is generated by its π-system of finite intersections of evaluation
preimages. -/
theorem prmEvalSigma_eq_generateFrom (R : Set E) :
    prmEvalSigma K X m R = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R) := by
  show (⨆ B : prmEvalIndex m R,
      MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)
    = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R)
  rw [prmEvalPiSystem,
    generateFrom_piiUnionInter_measurableSet
      (fun B : prmEvalIndex m R =>
        MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance) Set.univ,
    iSup_univ]

end ProbabilityTheory
