/-
Copyright (c) 2026 LeanLevy Contributors. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: LeanLevy Contributors
-/
import Mathlib.MeasureTheory.PiSystem
import LeanLevy.RandomMeasure.PoissonRandomMeasure

/-!
# Evaluation sigma-algebras of a Poisson random measure

Given the `poissonRandomMeasure K X` of a Poisson point family, a natural family of sub-sigma-algebras
on the sample space `Ω` records only the information carried by the counts inside a region `R ⊆ E`.
For a measurable subset `B ⊆ R` of finite intensity mass, the evaluation `ω ↦ poissonRandomMeasure K X ω B`
is a random variable, and the **evaluation sigma-algebra** `prmEvalSigma K X m R` is the least
sigma-algebra making all such evaluations measurable. This file defines that sigma-algebra, records its
basic order properties, and exhibits the generating π-system of finite intersections of evaluation
preimages.

## Main definitions

* `ProbabilityTheory.prmEvalIndex` — the index of admissible evaluation sets inside a region: measurable
  subsets of finite intensity mass.
* `ProbabilityTheory.prmEvalSigma` — the sigma-algebra generated by the finite-mass evaluations of the
  random measure inside a region `R`.
* `ProbabilityTheory.prmEvalPiSystem` — the generating π-system of finite intersections of evaluation
  preimages inside `R`.

## Main results

* `ProbabilityTheory.prmEvalSigma_mono` — the evaluation sigma-algebras grow with the region.
* `ProbabilityTheory.prmEvalSigma_le` — each evaluation sigma-algebra is a sub-sigma-algebra of the
  ambient one, given measurability of the counts and points.
* `ProbabilityTheory.measurable_prmEvalSigma_apply` — every finite-mass evaluation inside `R` is
  measurable with respect to `prmEvalSigma K X m R`.
* `ProbabilityTheory.measurable_lintegral_poissonRandomMeasure_prmEvalSigma` — the Lebesgue integral
  of a region-supported function against the random measure is measurable with respect to the
  evaluation sigma-algebra of the region.
* `ProbabilityTheory.isPiSystem_prmEvalPiSystem` — the generating family is a π-system.
* `ProbabilityTheory.prmEvalSigma_eq_generateFrom` — the evaluation sigma-algebra is generated by that
  π-system.
* `ProbabilityTheory.indepFun_poissonRandomMeasure_families` — two finite families of finite-mass
  evaluation sets, mutually disjoint across the families, give independent evaluation processes.
* `ProbabilityTheory.indep_prmEvalSigma` — **the Poisson random measure is independently scattered at
  the sigma-algebra level:** the evaluation sigma-algebras of two disjoint regions are independent.
-/

open MeasureTheory

open scoped ENNReal

namespace ProbabilityTheory

variable {Ω E : Type} [MeasurableSpace Ω] [MeasurableSpace E] {K : ℕ → Ω → ℕ} {X : ℕ → ℕ → Ω → E}
  {m : Measure E}

/-- The index of admissible evaluation sets inside a region: measurable, contained, finite mass. -/
def prmEvalIndex (m : Measure E) (R : Set E) : Type :=
  {B : Set E // MeasurableSet B ∧ B ⊆ R ∧ m B < ⊤}

/-- The σ-algebra generated by the finite-mass evaluations of the random measure inside `R`. -/
@[reducible] noncomputable def prmEvalSigma (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E)
    (R : Set E) : MeasurableSpace Ω :=
  ⨆ B : prmEvalIndex m R,
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebras grow with the region: a larger region admits more evaluation sets. -/
theorem prmEvalSigma_mono {R S : Set E} (hRS : R ⊆ S) :
    prmEvalSigma K X m R ≤ prmEvalSigma K X m S :=
  iSup_le fun B => le_iSup_of_le ⟨B.1, B.2.1, B.2.2.1.trans hRS, B.2.2.2⟩ le_rfl

/-- Each evaluation σ-algebra is a sub-σ-algebra of the ambient one, provided the counts and points
of the underlying family are measurable. -/
theorem prmEvalSigma_le (hK : ∀ k, Measurable (K k)) (hX : ∀ k n, Measurable (X k n)) (R : Set E) :
    prmEvalSigma K X m R ≤ ‹MeasurableSpace Ω› :=
  iSup_le fun B => (measurable_poissonRandomMeasure_apply hK hX B.2.1).comap_le

omit [MeasurableSpace Ω] in
/-- Every finite-mass evaluation inside `R` is measurable with respect to `prmEvalSigma K X m R`. -/
theorem measurable_prmEvalSigma_apply {B R : Set E} (hB : MeasurableSet B) (hBR : B ⊆ R)
    (hfin : m B < ⊤) :
    Measurable[prmEvalSigma K X m R] fun ω => poissonRandomMeasure K X ω B :=
  Measurable.of_comap_le <| le_iSup (fun B' : prmEvalIndex m R =>
    MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B'.1) inferInstance)
    ⟨B, hB, hBR, hfin⟩

omit [MeasurableSpace Ω] in
/-- The Lebesgue integral of a region-supported function against the random measure is measurable
with respect to the evaluation σ-algebra of the region. Every nonzero-value fiber of a monotone
simple-function approximant of `g` lies inside `R`, so the approximant's integral is a finite sum of
finite-mass evaluations inside `R`; the integral is their countable supremum. -/
theorem measurable_lintegral_poissonRandomMeasure_prmEvalSigma {R : Set E}
    (_hR : MeasurableSet R) (hRfin : m R < ⊤) {g : E → ℝ≥0∞} (hg : Measurable g)
    (hgR : ∀ x, x ∉ R → g x = 0) :
    Measurable[prmEvalSigma K X m R]
      fun ω => ∫⁻ x, g x ∂(poissonRandomMeasure K X ω) := by
  -- every nonzero-value fiber of an approximant sits inside `R`
  have hfiber : ∀ (n : ℕ) {y : ℝ≥0∞}, y ≠ 0 → SimpleFunc.eapprox g n ⁻¹' {y} ⊆ R := by
    intro n y hy x hx
    rw [Set.mem_preimage, Set.mem_singleton_iff] at hx
    by_contra hxR
    have hle : SimpleFunc.eapprox g n x ≤ g x := by
      have h := le_iSup (fun k => SimpleFunc.eapprox g k x) n
      rwa [SimpleFunc.iSup_eapprox_apply hg x] at h
    rw [hx, hgR x hxR, le_zero_iff] at hle
    exact hy hle
  -- each approximant's simple-function integral is measurable in `prmEvalSigma R`
  have hsimple : ∀ n : ℕ, Measurable[prmEvalSigma K X m R]
      fun ω => (SimpleFunc.eapprox g n).lintegral (poissonRandomMeasure K X ω) := by
    intro n
    simp only [SimpleFunc.lintegral]
    refine Finset.measurable_sum _ fun y _ => ?_
    by_cases hy : y = 0
    · simp only [hy, zero_mul]; exact measurable_const
    · exact (measurable_prmEvalSigma_apply ((SimpleFunc.eapprox g n).measurableSet_fiber y)
        (hfiber n hy) (lt_of_le_of_lt (measure_mono (hfiber n hy)) hRfin)).const_mul y
  -- the integral is the countable supremum of the approximants' integrals
  have hcongr : (fun ω => ∫⁻ x, g x ∂(poissonRandomMeasure K X ω))
      = fun ω => ⨆ n : ℕ, (SimpleFunc.eapprox g n).lintegral (poissonRandomMeasure K X ω) :=
    funext fun ω => lintegral_eq_iSup_eapprox_lintegral hg
  rw [hcongr]
  exact Measurable.iSup hsimple

/-- The generating π-system: finite intersections of evaluation preimages inside `R`. -/
def prmEvalPiSystem (K : ℕ → Ω → ℕ) (X : ℕ → ℕ → Ω → E) (m : Measure E) (R : Set E) :
    Set (Set Ω) :=
  piiUnionInter (fun B : prmEvalIndex m R =>
    {A | MeasurableSet[MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1)
      inferInstance] A}) Set.univ

omit [MeasurableSpace Ω] in
/-- The generating family of evaluation preimages is a π-system. -/
theorem isPiSystem_prmEvalPiSystem {R : Set E} : IsPiSystem (prmEvalPiSystem K X m R) :=
  isPiSystem_piiUnionInter _ (fun B : prmEvalIndex m R => @MeasurableSpace.isPiSystem_measurableSet Ω
    (MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)) Set.univ

omit [MeasurableSpace Ω] in
/-- The evaluation σ-algebra is generated by its π-system of finite intersections of evaluation
preimages. -/
theorem prmEvalSigma_eq_generateFrom (R : Set E) :
    prmEvalSigma K X m R = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R) := by
  show (⨆ B : prmEvalIndex m R,
      MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance)
    = MeasurableSpace.generateFrom (prmEvalPiSystem K X m R)
  rw [prmEvalPiSystem,
    generateFrom_piiUnionInter_measurableSet
      (fun B : prmEvalIndex m R =>
        MeasurableSpace.comap (fun ω => poissonRandomMeasure K X ω B.1) inferInstance) Set.univ,
    iSup_univ]

/-! ### Atomization of a finite family of evaluation sets

To reduce cross-family independence to the mutual independence of counts over a pairwise disjoint
family, we refine a finite family `B : ι → Set E` into its atoms. For a finset `J ⊆ ι`, the atom
`evalAtom B J` collects the points lying in `B i` for every `i ∈ J` and outside `B i` for every
`i ∉ J`. Distinct atoms are disjoint, each atom sits inside every `B i` with `i ∈ J`, and `B i` is
the disjoint union of the atoms whose index set contains `i`. The empty index set is sent to `∅` so
that every atom has finite intensity mass. -/

section Atomization

variable {ι : Type} {B : ι → Set E}

/-- The atom of a finite family `B : ι → Set E` at a finset `J`: the points lying in `B i` for every
`i ∈ J` and outside `B i` for every `i ∉ J`; the empty index set is sent to `∅`. -/
private def evalAtom (B : ι → Set E) (J : Finset ι) : Set E :=
  if J.Nonempty then (⋂ i ∈ J, B i) ∩ ⋂ i ∉ J, (B i)ᶜ else ∅

omit [MeasurableSpace E] in
private lemma evalAtom_of_nonempty {J : Finset ι} (hJ : J.Nonempty) :
    evalAtom B J = (⋂ i ∈ J, B i) ∩ ⋂ i ∉ J, (B i)ᶜ :=
  if_pos hJ

omit [MeasurableSpace E] in
private lemma evalAtom_empty : evalAtom B ∅ = ∅ :=
  if_neg (by simp)

omit [MeasurableSpace E] in
private lemma evalAtom_subset {J : Finset ι} {i : ι} (hiJ : i ∈ J) :
    evalAtom B J ⊆ B i := by
  rw [evalAtom_of_nonempty ⟨i, hiJ⟩]
  exact Set.inter_subset_left.trans (Set.iInter₂_subset i hiJ)

omit [MeasurableSpace E] in
private lemma evalAtom_subset_compl {J : Finset ι} {i : ι} (hJ : J.Nonempty)
    (hiJ : i ∉ J) : evalAtom B J ⊆ (B i)ᶜ := by
  rw [evalAtom_of_nonempty hJ]
  exact Set.inter_subset_right.trans (Set.iInter₂_subset i hiJ)

omit [MeasurableSpace E] in
private lemma evalAtom_subset_iUnion {J : Finset ι} :
    evalAtom B J ⊆ ⋃ i, B i := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty]; exact Set.empty_subset _
  · obtain ⟨i, hi⟩ := hJ
    exact (evalAtom_subset hi).trans (Set.subset_iUnion _ i)

private lemma measurableSet_evalAtom [Fintype ι] (hBm : ∀ i, MeasurableSet (B i))
    (J : Finset ι) : MeasurableSet (evalAtom B J) := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty]; exact MeasurableSet.empty
  · rw [evalAtom_of_nonempty hJ]
    exact (Finset.measurableSet_biInter J fun i _ => hBm i).inter
      (MeasurableSet.iInter fun i => MeasurableSet.iInter fun _ => (hBm i).compl)

private lemma measure_evalAtom_lt_top (hBfin : ∀ i, m (B i) < ⊤) (J : Finset ι) :
    m (evalAtom B J) < ⊤ := by
  rcases J.eq_empty_or_nonempty with rfl | hJ
  · rw [evalAtom_empty, measure_empty]; exact ENNReal.zero_lt_top
  · obtain ⟨i, hi⟩ := hJ
    exact lt_of_le_of_lt (measure_mono (evalAtom_subset hi)) (hBfin i)

omit [MeasurableSpace E] in
private lemma disjoint_evalAtom_of_mem_notMem {J J' : Finset ι} {i : ι}
    (hiJ : i ∈ J) (hiJ' : i ∉ J') : Disjoint (evalAtom B J) (evalAtom B J') := by
  rcases J'.eq_empty_or_nonempty with rfl | hJ'
  · rw [evalAtom_empty]; exact disjoint_bot_right
  · exact Disjoint.mono (evalAtom_subset hiJ) (evalAtom_subset_compl hJ' hiJ') disjoint_compl_right

omit [MeasurableSpace E] in
private lemma pairwise_disjoint_evalAtom :
    Pairwise (Function.onFun Disjoint (evalAtom B)) := by
  intro J J' hJJ'
  show Disjoint (evalAtom B J) (evalAtom B J')
  have hne : ¬ ∀ i, i ∈ J ↔ i ∈ J' := fun h => hJJ' (Finset.ext h)
  push Not at hne
  obtain ⟨i, hi⟩ := hne
  rcases hi with ⟨hiJ, hiJ'⟩ | ⟨hiJ, hiJ'⟩
  · exact disjoint_evalAtom_of_mem_notMem hiJ hiJ'
  · exact (disjoint_evalAtom_of_mem_notMem hiJ' hiJ).symm

omit [MeasurableSpace E] in
private lemma biUnion_evalAtom [Fintype ι] [DecidableEq ι] (i : ι) :
    B i = ⋃ J ∈ Finset.univ.filter (fun J => i ∈ J), evalAtom B J := by
  classical
  ext x
  simp only [Set.mem_iUnion, Finset.mem_filter, Finset.mem_univ, true_and, exists_prop]
  constructor
  · intro hx
    refine ⟨Finset.univ.filter (fun j => x ∈ B j), Finset.mem_filter.mpr ⟨Finset.mem_univ i, hx⟩, ?_⟩
    have hne : (Finset.univ.filter (fun j => x ∈ B j)).Nonempty :=
      ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hx⟩⟩
    rw [evalAtom_of_nonempty hne]
    refine ⟨Set.mem_iInter₂.mpr fun j hj => (Finset.mem_filter.mp hj).2, ?_⟩
    exact Set.mem_iInter₂.mpr fun j hj hxBj =>
      hj (Finset.mem_filter.mpr ⟨Finset.mem_univ j, hxBj⟩)
  · rintro ⟨J, hiJ, hxJ⟩
    exact evalAtom_subset hiJ hxJ

omit [MeasurableSpace Ω] in
private lemma poissonRandomMeasure_apply_biUnion_evalAtom [Fintype ι] [DecidableEq ι]
    (hBm : ∀ i, MeasurableSet (B i)) (ω : Ω) (i : ι) :
    poissonRandomMeasure K X ω (B i)
      = ∑ J ∈ Finset.univ.filter (fun J => i ∈ J),
          poissonRandomMeasure K X ω (evalAtom B J) := by
  conv_lhs => rw [biUnion_evalAtom (B := B) i]
  rw [measure_biUnion_finset (pairwise_disjoint_evalAtom.set_pairwise _)
    (fun J _ => measurableSet_evalAtom hBm J)]

end Atomization

/-! ### Independence across disjoint families

The Poisson random measure is independently scattered: evaluations over regions that are set-wise
disjoint carry no information about one another. We first prove the process-level statement for two
finite families and then promote it to independence of the full evaluation sigma-algebras. -/

section Independence

variable {μ : Measure Ω} [SigmaFinite m] [Nonempty E]

/-- Cross-family independence: two finite families of finite-mass evaluation sets, with every set of
the first family disjoint from every set of the second (no disjointness required within a family),
give independent evaluation processes. -/
theorem indepFun_poissonRandomMeasure_families [IsProbabilityMeasure μ]
    (hd : IsPoissonPointFamily K X m μ) {ιB ιC : Type} [Fintype ιB] [Fintype ιC]
    {B : ιB → Set E} {C : ιC → Set E}
    (hBm : ∀ i, MeasurableSet (B i)) (hCm : ∀ j, MeasurableSet (C j))
    (hBfin : ∀ i, m (B i) < ⊤) (hCfin : ∀ j, m (C j) < ⊤)
    (hBC : ∀ i j, Disjoint (B i) (C j)) :
    IndepFun (fun ω (i : ιB) => poissonRandomMeasure K X ω (B i))
      (fun ω (j : ιC) => poissonRandomMeasure K X ω (C j)) μ := by
  classical
  have hAm : ∀ k, MeasurableSet (Sum.elim (evalAtom B) (evalAtom C) k) := by
    rintro (J | J)
    · exact measurableSet_evalAtom hBm J
    · exact measurableSet_evalAtom hCm J
  have hAfin : ∀ k, m (Sum.elim (evalAtom B) (evalAtom C) k) < ⊤ := by
    rintro (J | J)
    · exact measure_evalAtom_lt_top hBfin J
    · exact measure_evalAtom_lt_top hCfin J
  have hBCU : Disjoint (⋃ i, B i) (⋃ j, C j) :=
    Set.disjoint_iUnion_left.mpr fun i => Set.disjoint_iUnion_right.mpr fun j => hBC i j
  have hAdisj : Pairwise (Function.onFun Disjoint (Sum.elim (evalAtom B) (evalAtom C))) := by
    rintro (J | J) (J' | J') hne
    · exact pairwise_disjoint_evalAtom (Sum.inl_injective.ne_iff.mp hne)
    · exact hBCU.mono evalAtom_subset_iUnion evalAtom_subset_iUnion
    · exact (hBCU.mono evalAtom_subset_iUnion evalAtom_subset_iUnion).symm
    · exact pairwise_disjoint_evalAtom (Sum.inr_injective.ne_iff.mp hne)
  have hiIndep := iIndepFun_poissonRandomMeasure_apply hd hAm hAfin hAdisj
  have hmeas : ∀ k, Measurable
      (fun ω => poissonRandomMeasure K X ω (Sum.elim (evalAtom B) (evalAtom C) k)) :=
    fun k => measurable_poissonRandomMeasure_apply hd.measurable_count hd.measurable_point (hAm k)
  set S := Finset.univ.map (⟨Sum.inl, Sum.inl_injective⟩ : Finset ιB ↪ _) with hS
  set T := Finset.univ.map (⟨Sum.inr, Sum.inr_injective⟩ : Finset ιC ↪ _) with hT
  have hST : Disjoint S T := by
    rw [Finset.disjoint_left]
    intro x hxS hxT
    rw [hS, Finset.mem_map] at hxS
    rw [hT, Finset.mem_map] at hxT
    obtain ⟨J, -, rfl⟩ := hxS
    obtain ⟨J', -, hJ'⟩ := hxT
    exact Sum.inl_ne_inr hJ'.symm
  have hsplit := hiIndep.indepFun_finset S T hST hmeas
  set φ : (↥S → ℝ≥0∞) → (ιB → ℝ≥0∞) :=
    fun g i => ∑ J ∈ Finset.univ.filter (fun J => i ∈ J),
      g ⟨Sum.inl J, by rw [hS]; exact Finset.mem_map_of_mem _ (Finset.mem_univ J)⟩ with hφ
  set ψ : (↥T → ℝ≥0∞) → (ιC → ℝ≥0∞) :=
    fun g j => ∑ J ∈ Finset.univ.filter (fun J => j ∈ J),
      g ⟨Sum.inr J, by rw [hT]; exact Finset.mem_map_of_mem _ (Finset.mem_univ J)⟩ with hψ
  have hφmeas : Measurable φ := by
    rw [hφ]
    exact measurable_pi_lambda _ fun i => Finset.measurable_sum _ fun J _ => measurable_pi_apply _
  have hψmeas : Measurable ψ := by
    rw [hψ]
    exact measurable_pi_lambda _ fun j => Finset.measurable_sum _ fun J _ => measurable_pi_apply _
  have key := hsplit.comp hφmeas hψmeas
  have hφeq : (fun ω (i : ιB) => poissonRandomMeasure K X ω (B i))
      = φ ∘ fun ω (k : ↥S) => poissonRandomMeasure K X ω (Sum.elim (evalAtom B) (evalAtom C) k.1) := by
    funext ω i
    rw [poissonRandomMeasure_apply_biUnion_evalAtom hBm ω i]
    simp only [Function.comp_apply, hφ, Sum.elim_inl]
  have hψeq : (fun ω (j : ιC) => poissonRandomMeasure K X ω (C j))
      = ψ ∘ fun ω (k : ↥T) => poissonRandomMeasure K X ω (Sum.elim (evalAtom B) (evalAtom C) k.1) := by
    funext ω j
    rw [poissonRandomMeasure_apply_biUnion_evalAtom hCm ω j]
    simp only [Function.comp_apply, hψ, Sum.elim_inr]
  rw [hφeq, hψeq]
  exact key

/-- **The Poisson random measure is independently scattered at the sigma-algebra level:** the
evaluation sigma-algebras of two disjoint regions are independent. -/
theorem indep_prmEvalSigma [IsProbabilityMeasure μ] (hd : IsPoissonPointFamily K X m μ)
    {R S : Set E} (hRS : Disjoint R S) :
    Indep (prmEvalSigma K X m R) (prmEvalSigma K X m S) μ := by
  classical
  rw [prmEvalSigma_eq_generateFrom, prmEvalSigma_eq_generateFrom]
  refine IndepSets.indep' (fun s hs => ?_) (fun s hs => ?_)
    isPiSystem_prmEvalPiSystem isPiSystem_prmEvalPiSystem ?_
  · have h1 : MeasurableSet[MeasurableSpace.generateFrom (prmEvalPiSystem K X m R)] s :=
      MeasurableSpace.measurableSet_generateFrom hs
    rw [← prmEvalSigma_eq_generateFrom] at h1
    exact prmEvalSigma_le hd.measurable_count hd.measurable_point R s h1
  · have h1 : MeasurableSet[MeasurableSpace.generateFrom (prmEvalPiSystem K X m S)] s :=
      MeasurableSpace.measurableSet_generateFrom hs
    rw [← prmEvalSigma_eq_generateFrom] at h1
    exact prmEvalSigma_le hd.measurable_count hd.measurable_point S s h1
  · rw [IndepSets_iff]
    intro t1 t2 ht1 ht2
    obtain ⟨tR, -, fR, hfR, ht1eq⟩ := ht1
    obtain ⟨tS, -, fS, hfS, ht2eq⟩ := ht2
    have hURspec : ∀ B : ↥tR, ∃ U, MeasurableSet U ∧
        (fun ω => poissonRandomMeasure K X ω B.1.1) ⁻¹' U = fR B.1 :=
      fun B => MeasurableSpace.measurableSet_comap.mp (hfR B.1 B.2)
    have hUSspec : ∀ C : ↥tS, ∃ U, MeasurableSet U ∧
        (fun ω => poissonRandomMeasure K X ω C.1.1) ⁻¹' U = fS C.1 :=
      fun C => MeasurableSpace.measurableSet_comap.mp (hfS C.1 C.2)
    choose UR hURm hUReq using hURspec
    choose US hUSm hUSeq using hUSspec
    have hfam := indepFun_poissonRandomMeasure_families hd
      (B := fun B : ↥tR => (B.1.1 : Set E)) (C := fun C : ↥tS => (C.1.1 : Set E))
      (fun B => B.1.2.1) (fun C => C.1.2.1) (fun B => B.1.2.2.2) (fun C => C.1.2.2.2)
      (fun B C => (hRS.mono_left B.1.2.2.1).mono_right C.1.2.2.1)
    have hFR : (fun ω (B : ↥tR) => poissonRandomMeasure K X ω B.1.1) ⁻¹' (Set.univ.pi UR) = t1 := by
      rw [ht1eq]
      ext ω
      simp only [Set.mem_preimage, Set.mem_pi, Set.mem_univ, true_implies, Set.mem_iInter]
      constructor
      · intro h B hB
        have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω (⟨B, hB⟩ : ↥tR).1.1) ⁻¹' (UR ⟨B, hB⟩) :=
          h ⟨B, hB⟩
        rw [hUReq ⟨B, hB⟩] at hmem
        exact hmem
      · intro h B
        have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω B.1.1) ⁻¹' (UR B) := by
          rw [hUReq B]; exact h B.1 B.2
        exact hmem
    have hGS : (fun ω (C : ↥tS) => poissonRandomMeasure K X ω C.1.1) ⁻¹' (Set.univ.pi US) = t2 := by
      rw [ht2eq]
      ext ω
      simp only [Set.mem_preimage, Set.mem_pi, Set.mem_univ, true_implies, Set.mem_iInter]
      constructor
      · intro h C hC
        have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω (⟨C, hC⟩ : ↥tS).1.1) ⁻¹' (US ⟨C, hC⟩) :=
          h ⟨C, hC⟩
        rw [hUSeq ⟨C, hC⟩] at hmem
        exact hmem
      · intro h C
        have hmem : ω ∈ (fun ω => poissonRandomMeasure K X ω C.1.1) ⁻¹' (US C) := by
          rw [hUSeq C]; exact h C.1 C.2
        exact hmem
    rw [← hFR, ← hGS]
    exact hfam.measure_inter_preimage_eq_mul _ _
      (MeasurableSet.univ_pi hURm) (MeasurableSet.univ_pi hUSm)

end Independence

end ProbabilityTheory
